version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: knitdb
      POSTGRES_USER: knituser
      POSTGRES_PASSWORD: knitpass
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"

  web:
    build: .
    depends_on:
      - db
    ports:
      - "5050:5000"
    environment:
      POSTGRES_DB: knitdb
      POSTGRES_USER: knituser
      POSTGRES_PASSWORD: knitpass
      POSTGRES_HOST: db
    volumes:
      - .:/app

volumes:
  db-data:

